---
  - name: SAOS SOFTWARE
    hosts: all
    gather_facts: no

    tasks:
      - name: SAOS BACKUP
        netconf_config:
          backup: yes
          backup_options:
            filename: "{{ inventory_hostname }}_SAOS.txt"
            dir_path: /u000/Flexware_Backup
